sudo: required
services:
  - docker

before_install:
  - docker build -t dembyabella/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dembyabella/react-test npm test



# Build these images and push to dockerhub
# Log in to the docker CLI
after_success:
  - docker build -t dembyabella/multi-client ./client
  - docker build -t dembyabella/multi-nginx ./nginx
  - docker build -t dembyabella/multi-server ./server
  - docker build -t dembyabella/multi-worker ./worker
  # Emit password put it in login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them into docker hub
  - docker push dembyabella/multi-client
  - docker push dembyabella/multi-nginx
  - docker push dembyabella/multi-server
  - docker push dembyabella/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-248184876991
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
